from .client import Client
from .client_screen import Client_menu
from .person import Person
from .product_screen import *
from .rental import Rental
from .rental_screen import *
from .suit import Suit
from .supplier import Supplier
from .supplier_screen import Supplier_menu