from .Classes.client import Client
from .client_screen import Client_menu
from .Classes.person import Person
from .product_screen import *
from .Classes.rental import Rental
from .rental_screen import *
from .Classes.suit import Suit
from .Classes.supplier import Supplier
from .supplier_screen import Supplier_menu